import { TimeZone } from './types';

// Helper to get local
const localZone = Intl.DateTimeFormat().resolvedOptions().timeZone;

export const ALL_ZONES: TimeZone[] = [
  // --- Special ---
  { id: 'local', city: 'My Location', country: 'Local Time', iana: localZone, flag: '📍' },
  
  // --- Africa ---
  { id: 'dz', city: 'Algiers', country: 'Algeria', iana: 'Africa/Algiers', flag: '🇩🇿' },
  { id: 'ao', city: 'Luanda', country: 'Angola', iana: 'Africa/Luanda', flag: '🇦🇴' },
  { id: 'bj', city: 'Porto-Novo', country: 'Benin', iana: 'Africa/Porto-Novo', flag: '🇧🇯' },
  { id: 'bw', city: 'Gaborone', country: 'Botswana', iana: 'Africa/Gaborone', flag: '🇧🇼' },
  { id: 'bf', city: 'Ouagadougou', country: 'Burkina Faso', iana: 'Africa/Ouagadougou', flag: '🇧🇫' },
  { id: 'bi', city: 'Gitega', country: 'Burundi', iana: 'Africa/Bujumbura', flag: '🇧🇮' },
  { id: 'cv', city: 'Praia', country: 'Cabo Verde', iana: 'Atlantic/Cape_Verde', flag: '🇨🇻' },
  { id: 'cm', city: 'Yaoundé', country: 'Cameroon', iana: 'Africa/Douala', flag: '🇨🇲' },
  { id: 'cf', city: 'Bangui', country: 'Central African Republic', iana: 'Africa/Bangui', flag: '🇨🇫' },
  { id: 'td', city: 'N\'Djamena', country: 'Chad', iana: 'Africa/Ndjamena', flag: '🇹🇩' },
  { id: 'km', city: 'Moroni', country: 'Comoros', iana: 'Indian/Comoro', flag: '🇰🇲' },
  { id: 'cd', city: 'Kinshasa', country: 'DR Congo', iana: 'Africa/Kinshasa', flag: '🇨🇩' },
  { id: 'cg', city: 'Brazzaville', country: 'Republic of the Congo', iana: 'Africa/Brazzaville', flag: '🇨🇬' },
  { id: 'ci', city: 'Yamoussoukro', country: 'Côte d\'Ivoire', iana: 'Africa/Abidjan', flag: '🇨🇮' },
  { id: 'dj', city: 'Djibouti', country: 'Djibouti', iana: 'Africa/Djibouti', flag: '🇩🇯' },
  { id: 'eg', city: 'Cairo', country: 'Egypt', iana: 'Africa/Cairo', flag: '🇪🇬' },
  { id: 'gq', city: 'Malabo', country: 'Equatorial Guinea', iana: 'Africa/Malabo', flag: '🇬🇶' },
  { id: 'er', city: 'Asmara', country: 'Eritrea', iana: 'Africa/Asmara', flag: '🇪🇷' },
  { id: 'sz', city: 'Mbabane', country: 'Eswatini', iana: 'Africa/Mbabane', flag: '🇸🇿' },
  { id: 'et', city: 'Addis Ababa', country: 'Ethiopia', iana: 'Africa/Addis_Ababa', flag: '🇪🇹' },
  { id: 'ga', city: 'Libreville', country: 'Gabon', iana: 'Africa/Libreville', flag: '🇬🇦' },
  { id: 'gm', city: 'Banjul', country: 'Gambia', iana: 'Africa/Banjul', flag: '🇬🇲' },
  { id: 'gh', city: 'Accra', country: 'Ghana', iana: 'Africa/Accra', flag: '🇬🇭' },
  { id: 'gn', city: 'Conakry', country: 'Guinea', iana: 'Africa/Conakry', flag: '🇬🇳' },
  { id: 'gw', city: 'Bissau', country: 'Guinea-Bissau', iana: 'Africa/Bissau', flag: '🇬🇼' },
  { id: 'ke', city: 'Nairobi', country: 'Kenya', iana: 'Africa/Nairobi', flag: '🇰🇪' },
  { id: 'ls', city: 'Maseru', country: 'Lesotho', iana: 'Africa/Maseru', flag: '🇱🇸' },
  { id: 'lr', city: 'Monrovia', country: 'Liberia', iana: 'Africa/Monrovia', flag: '🇱🇷' },
  { id: 'ly', city: 'Tripoli', country: 'Libya', iana: 'Africa/Tripoli', flag: '🇱🇾' },
  { id: 'mg', city: 'Antananarivo', country: 'Madagascar', iana: 'Indian/Antananarivo', flag: '🇲🇬' },
  { id: 'mw', city: 'Lilongwe', country: 'Malawi', iana: 'Africa/Blantyre', flag: '🇲🇼' },
  { id: 'ml', city: 'Bamako', country: 'Mali', iana: 'Africa/Bamako', flag: '🇲🇱' },
  { id: 'mr', city: 'Nouakchott', country: 'Mauritania', iana: 'Africa/Nouakchott', flag: '🇲🇷' },
  { id: 'mu', city: 'Port Louis', country: 'Mauritius', iana: 'Indian/Mauritius', flag: '🇲🇺' },
  { id: 'ma', city: 'Casablanca', country: 'Morocco', iana: 'Africa/Casablanca', flag: '🇲🇦' },
  { id: 'mz', city: 'Maputo', country: 'Mozambique', iana: 'Africa/Maputo', flag: '🇲🇿' },
  { id: 'na', city: 'Windhoek', country: 'Namibia', iana: 'Africa/Windhoek', flag: '🇳🇦' },
  { id: 'ne', city: 'Niamey', country: 'Niger', iana: 'Africa/Niamey', flag: '🇳🇪' },
  { id: 'ng', city: 'Lagos', country: 'Nigeria', iana: 'Africa/Lagos', flag: '🇳🇬' },
  { id: 'rw', city: 'Kigali', country: 'Rwanda', iana: 'Africa/Kigali', flag: '🇷🇼' },
  { id: 'st', city: 'São Tomé', country: 'Sao Tome & Principe', iana: 'Africa/Sao_Tome', flag: '🇸🇹' },
  { id: 'sn', city: 'Dakar', country: 'Senegal', iana: 'Africa/Dakar', flag: '🇸🇳' },
  { id: 'sc', city: 'Victoria', country: 'Seychelles', iana: 'Indian/Mahe', flag: '🇸🇨' },
  { id: 'sl', city: 'Freetown', country: 'Sierra Leone', iana: 'Africa/Freetown', flag: '🇸🇱' },
  { id: 'so', city: 'Mogadishu', country: 'Somalia', iana: 'Africa/Mogadishu', flag: '🇸🇴' },
  { id: 'za', city: 'Johannesburg', country: 'South Africa', iana: 'Africa/Johannesburg', flag: '🇿🇦' },
  { id: 'ss', city: 'Juba', country: 'South Sudan', iana: 'Africa/Juba', flag: '🇸🇸' },
  { id: 'sd', city: 'Khartoum', country: 'Sudan', iana: 'Africa/Khartoum', flag: '🇸🇩' },
  { id: 'tz', city: 'Dodoma', country: 'Tanzania', iana: 'Africa/Dar_es_Salaam', flag: '🇹🇿' },
  { id: 'tg', city: 'Lomé', country: 'Togo', iana: 'Africa/Lome', flag: '🇹🇬' },
  { id: 'tn', city: 'Tunis', country: 'Tunisia', iana: 'Africa/Tunis', flag: '🇹🇳' },
  { id: 'ug', city: 'Kampala', country: 'Uganda', iana: 'Africa/Kampala', flag: '🇺🇬' },
  { id: 'zm', city: 'Lusaka', country: 'Zambia', iana: 'Africa/Lusaka', flag: '🇿🇲' },
  { id: 'zw', city: 'Harare', country: 'Zimbabwe', iana: 'Africa/Harare', flag: '🇿🇼' },

  // --- Asia ---
  { id: 'af', city: 'Kabul', country: 'Afghanistan', iana: 'Asia/Kabul', flag: '🇦🇫' },
  { id: 'am', city: 'Yerevan', country: 'Armenia', iana: 'Asia/Yerevan', flag: '🇦🇲' },
  { id: 'az', city: 'Baku', country: 'Azerbaijan', iana: 'Asia/Baku', flag: '🇦🇿' },
  { id: 'bh', city: 'Manama', country: 'Bahrain', iana: 'Asia/Bahrain', flag: '🇧🇭' },
  { id: 'bd', city: 'Dhaka', country: 'Bangladesh', iana: 'Asia/Dhaka', flag: '🇧🇩' },
  { id: 'bt', city: 'Thimphu', country: 'Bhutan', iana: 'Asia/Thimphu', flag: '🇧🇹' },
  { id: 'bn', city: 'Bandar Seri Begawan', country: 'Brunei', iana: 'Asia/Brunei', flag: '🇧🇳' },
  { id: 'kh', city: 'Phnom Penh', country: 'Cambodia', iana: 'Asia/Phnom_Penh', flag: '🇰🇭' },
  { id: 'cn', city: 'Shanghai', country: 'China', iana: 'Asia/Shanghai', flag: '🇨🇳' },
  { id: 'cy', city: 'Nicosia', country: 'Cyprus', iana: 'Asia/Nicosia', flag: '🇨🇾' },
  { id: 'ge', city: 'Tbilisi', country: 'Georgia', iana: 'Asia/Tbilisi', flag: '🇬🇪' },
  { id: 'hk', city: 'Hong Kong', country: 'Hong Kong', iana: 'Asia/Hong_Kong', flag: '🇭🇰' },
  { id: 'in', city: 'New Delhi', country: 'India', iana: 'Asia/Kolkata', flag: '🇮🇳' },
  { id: 'id', city: 'Jakarta', country: 'Indonesia', iana: 'Asia/Jakarta', flag: '🇮🇩' },
  { id: 'ir', city: 'Tehran', country: 'Iran', iana: 'Asia/Tehran', flag: '🇮🇷' },
  { id: 'iq', city: 'Baghdad', country: 'Iraq', iana: 'Asia/Baghdad', flag: '🇮🇶' },
  { id: 'il', city: 'Tel Aviv', country: 'Israel', iana: 'Asia/Jerusalem', flag: '🇮🇱' },
  { id: 'jp', city: 'Tokyo', country: 'Japan', iana: 'Asia/Tokyo', flag: '🇯🇵' },
  { id: 'jo', city: 'Amman', country: 'Jordan', iana: 'Asia/Amman', flag: '🇯🇴' },
  { id: 'kz', city: 'Almaty', country: 'Kazakhstan', iana: 'Asia/Almaty', flag: '🇰🇿' },
  { id: 'kw', city: 'Kuwait City', country: 'Kuwait', iana: 'Asia/Kuwait', flag: '🇰🇼' },
  { id: 'kg', city: 'Bishkek', country: 'Kyrgyzstan', iana: 'Asia/Bishkek', flag: '🇰🇬' },
  { id: 'la', city: 'Vientiane', country: 'Laos', iana: 'Asia/Vientiane', flag: '🇱🇦' },
  { id: 'lb', city: 'Beirut', country: 'Lebanon', iana: 'Asia/Beirut', flag: '🇱🇧' },
  { id: 'my', city: 'Kuala Lumpur', country: 'Malaysia', iana: 'Asia/Kuala_Lumpur', flag: '🇲🇾' },
  { id: 'mv', city: 'Malé', country: 'Maldives', iana: 'Indian/Maldives', flag: '🇲🇻' },
  { id: 'mn', city: 'Ulaanbaatar', country: 'Mongolia', iana: 'Asia/Ulaanbaatar', flag: '🇲🇳' },
  { id: 'mm', city: 'Yangon', country: 'Myanmar', iana: 'Asia/Yangon', flag: '🇲🇲' },
  { id: 'np', city: 'Kathmandu', country: 'Nepal', iana: 'Asia/Kathmandu', flag: '🇳🇵' },
  { id: 'kp', city: 'Pyongyang', country: 'North Korea', iana: 'Asia/Pyongyang', flag: '🇰🇵' },
  { id: 'om', city: 'Muscat', country: 'Oman', iana: 'Asia/Muscat', flag: '🇴🇲' },
  { id: 'pk', city: 'Karachi', country: 'Pakistan', iana: 'Asia/Karachi', flag: '🇵🇰' },
  { id: 'ph', city: 'Manila', country: 'Philippines', iana: 'Asia/Manila', flag: '🇵🇭' },
  { id: 'qa', city: 'Doha', country: 'Qatar', iana: 'Asia/Qatar', flag: '🇶🇦' },
  { id: 'sa', city: 'Riyadh', country: 'Saudi Arabia', iana: 'Asia/Riyadh', flag: '🇸🇦' },
  { id: 'sg', city: 'Singapore', country: 'Singapore', iana: 'Asia/Singapore', flag: '🇸🇬' },
  { id: 'kr', city: 'Seoul', country: 'South Korea', iana: 'Asia/Seoul', flag: '🇰🇷' },
  { id: 'lk', city: 'Colombo', country: 'Sri Lanka', iana: 'Asia/Colombo', flag: '🇱🇰' },
  { id: 'sy', city: 'Damascus', country: 'Syria', iana: 'Asia/Damascus', flag: '🇸🇾' },
  { id: 'tw', city: 'Taipei', country: 'Taiwan', iana: 'Asia/Taipei', flag: '🇹🇼' },
  { id: 'tj', city: 'Dushanbe', country: 'Tajikistan', iana: 'Asia/Dushanbe', flag: '🇹🇯' },
  { id: 'th', city: 'Bangkok', country: 'Thailand', iana: 'Asia/Bangkok', flag: '🇹🇭' },
  { id: 'tl', city: 'Dili', country: 'Timor-Leste', iana: 'Asia/Dili', flag: '🇹🇱' },
  { id: 'tr', city: 'Istanbul', country: 'Turkey', iana: 'Europe/Istanbul', flag: '🇹🇷' },
  { id: 'tm', city: 'Ashgabat', country: 'Turkmenistan', iana: 'Asia/Ashgabat', flag: '🇹🇲' },
  { id: 'ae', city: 'Dubai', country: 'UAE', iana: 'Asia/Dubai', flag: '🇦🇪' },
  { id: 'uz', city: 'Tashkent', country: 'Uzbekistan', iana: 'Asia/Tashkent', flag: '🇺🇿' },
  { id: 'vn', city: 'Ho Chi Minh', country: 'Vietnam', iana: 'Asia/Ho_Chi_Minh', flag: '🇻🇳' },
  { id: 'ye', city: 'Sana\'a', country: 'Yemen', iana: 'Asia/Aden', flag: '🇾🇪' },

  // --- Europe ---
  { id: 'al', city: 'Tirana', country: 'Albania', iana: 'Europe/Tirane', flag: '🇦🇱' },
  { id: 'ad', city: 'Andorra la Vella', country: 'Andorra', iana: 'Europe/Andorra', flag: '🇦🇩' },
  { id: 'at', city: 'Vienna', country: 'Austria', iana: 'Europe/Vienna', flag: '🇦🇹' },
  { id: 'by', city: 'Minsk', country: 'Belarus', iana: 'Europe/Minsk', flag: '🇧🇾' },
  { id: 'be', city: 'Brussels', country: 'Belgium', iana: 'Europe/Brussels', flag: '🇧🇪' },
  { id: 'ba', city: 'Sarajevo', country: 'Bosnia & Herzegovina', iana: 'Europe/Sarajevo', flag: '🇧🇦' },
  { id: 'bg', city: 'Sofia', country: 'Bulgaria', iana: 'Europe/Sofia', flag: '🇧🇬' },
  { id: 'hr', city: 'Zagreb', country: 'Croatia', iana: 'Europe/Zagreb', flag: '🇭🇷' },
  { id: 'cz', city: 'Prague', country: 'Czechia', iana: 'Europe/Prague', flag: '🇨🇿' },
  { id: 'dk', city: 'Copenhagen', country: 'Denmark', iana: 'Europe/Copenhagen', flag: '🇩🇰' },
  { id: 'ee', city: 'Tallinn', country: 'Estonia', iana: 'Europe/Tallinn', flag: '🇪🇪' },
  { id: 'fi', city: 'Helsinki', country: 'Finland', iana: 'Europe/Helsinki', flag: '🇫🇮' },
  { id: 'fr', city: 'Paris', country: 'France', iana: 'Europe/Paris', flag: '🇫🇷' },
  { id: 'de', city: 'Berlin', country: 'Germany', iana: 'Europe/Berlin', flag: '🇩🇪' },
  { id: 'gr', city: 'Athens', country: 'Greece', iana: 'Europe/Athens', flag: '🇬🇷' },
  { id: 'hu', city: 'Budapest', country: 'Hungary', iana: 'Europe/Budapest', flag: '🇭🇺' },
  { id: 'is', city: 'Reykjavik', country: 'Iceland', iana: 'Atlantic/Reykjavik', flag: '🇮🇸' },
  { id: 'ie', city: 'Dublin', country: 'Ireland', iana: 'Europe/Dublin', flag: '🇮🇪' },
  { id: 'it', city: 'Rome', country: 'Italy', iana: 'Europe/Rome', flag: '🇮🇹' },
  { id: 'xk', city: 'Pristina', country: 'Kosovo', iana: 'Europe/Belgrade', flag: '🇽🇰' },
  { id: 'lv', city: 'Riga', country: 'Latvia', iana: 'Europe/Riga', flag: '🇱🇻' },
  { id: 'li', city: 'Vaduz', country: 'Liechtenstein', iana: 'Europe/Vaduz', flag: '🇱🇮' },
  { id: 'lt', city: 'Vilnius', country: 'Lithuania', iana: 'Europe/Vilnius', flag: '🇱🇹' },
  { id: 'lu', city: 'Luxembourg', country: 'Luxembourg', iana: 'Europe/Luxembourg', flag: '🇱🇺' },
  { id: 'mt', city: 'Valletta', country: 'Malta', iana: 'Europe/Malta', flag: '🇲🇹' },
  { id: 'md', city: 'Chisinau', country: 'Moldova', iana: 'Europe/Chisinau', flag: '🇲🇩' },
  { id: 'mc', city: 'Monaco', country: 'Monaco', iana: 'Europe/Monaco', flag: '🇲🇨' },
  { id: 'me', city: 'Podgorica', country: 'Montenegro', iana: 'Europe/Podgorica', flag: '🇲🇪' },
  { id: 'nl', city: 'Amsterdam', country: 'Netherlands', iana: 'Europe/Amsterdam', flag: '🇳🇱' },
  { id: 'mk', city: 'Skopje', country: 'North Macedonia', iana: 'Europe/Skopje', flag: '🇲🇰' },
  { id: 'no', city: 'Oslo', country: 'Norway', iana: 'Europe/Oslo', flag: '🇳🇴' },
  { id: 'pl', city: 'Warsaw', country: 'Poland', iana: 'Europe/Warsaw', flag: '🇵🇱' },
  { id: 'pt', city: 'Lisbon', country: 'Portugal', iana: 'Europe/Lisbon', flag: '🇵🇹' },
  { id: 'ro', city: 'Bucharest', country: 'Romania', iana: 'Europe/Bucharest', flag: '🇷🇴' },
  { id: 'ru-mo', city: 'Moscow', country: 'Russia', iana: 'Europe/Moscow', flag: '🇷🇺' },
  { id: 'sm', city: 'San Marino', country: 'San Marino', iana: 'Europe/San_Marino', flag: '🇸🇲' },
  { id: 'rs', city: 'Belgrade', country: 'Serbia', iana: 'Europe/Belgrade', flag: '🇷🇸' },
  { id: 'sk', city: 'Bratislava', country: 'Slovakia', iana: 'Europe/Bratislava', flag: '🇸🇰' },
  { id: 'si', city: 'Ljubljana', country: 'Slovenia', iana: 'Europe/Ljubljana', flag: '🇸🇮' },
  { id: 'es', city: 'Madrid', country: 'Spain', iana: 'Europe/Madrid', flag: '🇪🇸' },
  { id: 'se', city: 'Stockholm', country: 'Sweden', iana: 'Europe/Stockholm', flag: '🇸🇪' },
  { id: 'ch', city: 'Zurich', country: 'Switzerland', iana: 'Europe/Zurich', flag: '🇨🇭' },
  { id: 'ua', city: 'Kyiv', country: 'Ukraine', iana: 'Europe/Kyiv', flag: '🇺🇦' },
  { id: 'gb', city: 'London', country: 'UK', iana: 'Europe/London', flag: '🇬🇧' },
  { id: 'va', city: 'Vatican City', country: 'Vatican City', iana: 'Europe/Vatican', flag: '🇻🇦' },

  // --- North America ---
  { id: 'ag', city: 'St. John\'s', country: 'Antigua & Barbuda', iana: 'America/Antigua', flag: '🇦🇬' },
  { id: 'bs', city: 'Nassau', country: 'Bahamas', iana: 'America/Nassau', flag: '🇧🇸' },
  { id: 'bb', city: 'Bridgetown', country: 'Barbados', iana: 'America/Barbados', flag: '🇧🇧' },
  { id: 'bz', city: 'Belmopan', country: 'Belize', iana: 'America/Belize', flag: '🇧🇿' },
  { id: 'ca-tor', city: 'Toronto', country: 'Canada', iana: 'America/Toronto', flag: '🇨🇦' },
  { id: 'ca-van', city: 'Vancouver', country: 'Canada', iana: 'America/Vancouver', flag: '🇨🇦' },
  { id: 'cr', city: 'San José', country: 'Costa Rica', iana: 'America/Costa_Rica', flag: '🇨🇷' },
  { id: 'cu', city: 'Havana', country: 'Cuba', iana: 'America/Havana', flag: '🇨🇺' },
  { id: 'dm', city: 'Roseau', country: 'Dominica', iana: 'America/Dominica', flag: '🇩🇲' },
  { id: 'do', city: 'Santo Domingo', country: 'Dominican Republic', iana: 'America/Santo_Domingo', flag: '🇩🇴' },
  { id: 'sv', city: 'San Salvador', country: 'El Salvador', iana: 'America/El_Salvador', flag: '🇸🇻' },
  { id: 'gd', city: 'St. George\'s', country: 'Grenada', iana: 'America/Grenada', flag: '🇬🇩' },
  { id: 'gt', city: 'Guatemala City', country: 'Guatemala', iana: 'America/Guatemala', flag: '🇬🇹' },
  { id: 'ht', city: 'Port-au-Prince', country: 'Haiti', iana: 'America/Port-au-Prince', flag: '🇭🇹' },
  { id: 'hn', city: 'Tegucigalpa', country: 'Honduras', iana: 'America/Tegucigalpa', flag: '🇭🇳' },
  { id: 'jm', city: 'Kingston', country: 'Jamaica', iana: 'America/Jamaica', flag: '🇯🇲' },
  { id: 'mx', city: 'Mexico City', country: 'Mexico', iana: 'America/Mexico_City', flag: '🇲🇽' },
  { id: 'ni', city: 'Managua', country: 'Nicaragua', iana: 'America/Managua', flag: '🇳🇮' },
  { id: 'pa', city: 'Panama City', country: 'Panama', iana: 'America/Panama', flag: '🇵🇦' },
  { id: 'kn', city: 'Basseterre', country: 'Saint Kitts & Nevis', iana: 'America/St_Kitts', flag: '🇰🇳' },
  { id: 'lc', city: 'Castries', country: 'Saint Lucia', iana: 'America/St_Lucia', flag: '🇱🇨' },
  { id: 'vc', city: 'Kingstown', country: 'St. Vincent & Grenadines', iana: 'America/St_Vincent', flag: '🇻🇨' },
  { id: 'tt', city: 'Port of Spain', country: 'Trinidad & Tobago', iana: 'America/Port_of_Spain', flag: '🇹🇹' },
  { id: 'us-ny', city: 'New York (EST)', country: 'USA', iana: 'America/New_York', flag: '🇺🇸' },
  { id: 'us-la', city: 'Los Angeles (PST)', country: 'USA', iana: 'America/Los_Angeles', flag: '🇺🇸' },
  { id: 'us-chi', city: 'Chicago (CST)', country: 'USA', iana: 'America/Chicago', flag: '🇺🇸' },

  // --- South America ---
  { id: 'ar', city: 'Buenos Aires', country: 'Argentina', iana: 'America/Argentina/Buenos_Aires', flag: '🇦🇷' },
  { id: 'bo', city: 'La Paz', country: 'Bolivia', iana: 'America/La_Paz', flag: '🇧🇴' },
  { id: 'br', city: 'São Paulo', country: 'Brazil', iana: 'America/Sao_Paulo', flag: '🇧🇷' },
  { id: 'cl', city: 'Santiago', country: 'Chile', iana: 'America/Santiago', flag: '🇨🇱' },
  { id: 'co', city: 'Bogotá', country: 'Colombia', iana: 'America/Bogota', flag: '🇨🇴' },
  { id: 'ec', city: 'Quito', country: 'Ecuador', iana: 'America/Guayaquil', flag: '🇪🇨' },
  { id: 'gy', city: 'Georgetown', country: 'Guyana', iana: 'America/Guyana', flag: '🇬🇾' },
  { id: 'py', city: 'Asunción', country: 'Paraguay', iana: 'America/Asuncion', flag: '🇵🇾' },
  { id: 'pe', city: 'Lima', country: 'Peru', iana: 'America/Lima', flag: '🇵🇪' },
  { id: 'sr', city: 'Paramaribo', country: 'Suriname', iana: 'America/Paramaribo', flag: '🇸🇷' },
  { id: 'uy', city: 'Montevideo', country: 'Uruguay', iana: 'America/Montevideo', flag: '🇺🇾' },
  { id: 've', city: 'Caracas', country: 'Venezuela', iana: 'America/Caracas', flag: '🇻🇪' },

  // --- Oceania ---
  { id: 'au-sy', city: 'Sydney', country: 'Australia', iana: 'Australia/Sydney', flag: '🇦🇺' },
  { id: 'fj', city: 'Suva', country: 'Fiji', iana: 'Pacific/Fiji', flag: '🇫🇯' },
  { id: 'ki', city: 'Tarawa', country: 'Kiribati', iana: 'Pacific/Tarawa', flag: '🇰🇮' },
  { id: 'mh', city: 'Majuro', country: 'Marshall Islands', iana: 'Pacific/Majuro', flag: '🇲🇭' },
  { id: 'fm', city: 'Palikir', country: 'Micronesia', iana: 'Pacific/Pohnpei', flag: '🇫🇲' },
  { id: 'nr', city: 'Yaren', country: 'Nauru', iana: 'Pacific/Nauru', flag: '🇳🇷' },
  { id: 'nz', city: 'Auckland', country: 'New Zealand', iana: 'Pacific/Auckland', flag: '🇳🇿' },
  { id: 'pw', city: 'Ngerulmud', country: 'Palau', iana: 'Pacific/Palau', flag: '🇵🇼' },
  { id: 'pg', city: 'Port Moresby', country: 'Papua New Guinea', iana: 'Pacific/Port_Moresby', flag: '🇵🇬' },
  { id: 'ws', city: 'Apia', country: 'Samoa', iana: 'Pacific/Apia', flag: '🇼🇸' },
  { id: 'sb', city: 'Honiara', country: 'Solomon Islands', iana: 'Pacific/Guadalcanal', flag: '🇸🇧' },
  { id: 'to', city: 'Nuku\'alofa', country: 'Tonga', iana: 'Pacific/Tongatapu', flag: '🇹🇴' },
  { id: 'tv', city: 'Funafuti', country: 'Tuvalu', iana: 'Pacific/Funafuti', flag: '🇹🇻' },
  { id: 'vu', city: 'Port Vila', country: 'Vanuatu', iana: 'Pacific/Efate', flag: '🇻🇺' },
];